sudo: required
language: python

services:
  - docker

before_install:
  - docker pull stpotter/pysplinefit:latest
  - export DOCKER_RUN="docker run -v ${TRAVIS_BUILD_DIR}:/home/test stpotter/pysplinefit:latest"

script:
  - ${DOCER_RUN} /bin/bash -l -c "python -m pytest"

notifications:
  email: false