sudo: required
language: python

services:
  - docker

before_install:
  - docker build -t pysplinefit
  - export DOCKER_RUN="docker run -v ${TRAVIS_BUILD_DIR}:/home/test pysplinefit"

script:
  - ${DOCER_RUN} /bin/bash -l -c "python -m pytest"

notifications:
  email: false